services:
  db:
    build:
      context: ./packages/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messengerv2_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: dockerpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  http-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres_user:dockerpassword@db:5432/messengerv2_db"
      JWT_SECRET: "your_jwt_secret" 
    command: pnpm --filter http-backend start
    depends_on:
      - db

  ws-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres_user:dockerpassword@db:5432/messengerv2_db"
      JWT_SECRET: "your_jwt_secret"
    command: pnpm --filter ws-backend start
    depends_on:
      - db

volumes:
  postgres_data: