version: '3.8'

services:
  db:
    build:
      context: ./packages/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messengerv2_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: dockerpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: