import type { Metadata } from "next";
import "./globals.css";
import { MyThemeProvider } from "./theme-provider"; // <-- 1. Import the provider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <MyThemeProvider>
          {children}
        </MyThemeProvider>
      </body>
    </html>
  );
}